steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/react-421001/react', '.']
  dir: '/workspace/React'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/react-421001/react']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
  'run', 
  'deploy', 
  'react',
  '--image', 
  'gcr.io/react-421001/react', 
  '--region', 
  'us-central1', 
  '--platform', 
  'managed',
  '--port', 
  '3000',
  '--cpu', 
  '1',
  '--memory', 
  '1Gi',
]
